## Phase 1: Environment Setup & Data Preparation
In this phase, we prepare our workspace and consolidate our datasets. The raw sales data is divided into separate monthly files within a designated directory. 

**Objectives for this phase:**
1. Import essential libraries (`pandas`, `os`).
2. Iterate through the target directory to locate all monthly `.csv` files.
3. Concatenate the individual datasets into one comprehensive dataframe.
4. Export the master dataset for the upcoming analytical phases.

In [26]:
# Import essential libraries for data manipulation and system path management
import pandas as pd
import os

In [27]:
# Define the path to the directory containing the monthly sales datasets
folder_path = "salesmonths"

# Extract and display the list of files in the directory to verify their presence
files = os.listdir(folder_path)
files

['sales_2023_01.csv',
 'sales_2023_02.csv',
 'sales_2023_03.csv',
 'sales_2023_04.csv',
 'sales_2023_05.csv',
 'sales_2023_06.csv',
 'sales_2023_07.csv',
 'sales_2023_08.csv',
 'sales_2023_09.csv',
 'sales_2023_10.csv',
 'sales_2023_11.csv',
 'sales_2023_12.csv',
 'sales_2024_01.csv',
 'sales_2024_02.csv',
 'sales_2024_03.csv',
 'sales_2024_04.csv',
 'sales_2024_05.csv',
 'sales_2024_06.csv',
 'sales_2024_07.csv',
 'sales_2024_08.csv',
 'sales_2024_09.csv',
 'sales_2024_10.csv',
 'sales_2024_11.csv',
 'sales_2024_12.csv',
 'sales_2025_01.csv',
 'sales_2025_02.csv',
 'sales_2025_03.csv',
 'sales_2025_04.csv',
 'sales_2025_05.csv',
 'sales_2025_06.csv',
 'sales_2025_07.csv',
 'sales_2025_08.csv',
 'sales_2025_09.csv',
 'sales_2025_10.csv',
 'sales_2025_11.csv',
 'sales_2025_12.csv']

In [28]:
# Define the directory containing the monthly datasets
folder_path = "salesmonths"

# Initialize an empty list to collect individual monthly dataframes
dfs = []

# Iterate through all files within the specified directory
for file in os.listdir(folder_path):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(folder_path, file))
        dfs.append(df)
        
# Concatenate all monthly dataframes into a single, unified dataframe
final_df = pd.concat(dfs, ignore_index=True)

In [29]:
# Export the consolidated dataframe to a new CSV file for future analysis
final_df.to_csv("all_sales.csv", index=False)

In [30]:
final_df.shape

(1080000, 13)

## Phase 2: Data Preparation & Feature Engineering
Before diving into exploratory data analysis, we must sanitize and enrich our dataset. This section covers the essential data preparation steps:

1. **Data Profiling:** Checking data structures and identifying duplicate records.
2. **Date Parsing:** Standardizing the `sale_date` column and extracting temporal features.
3. **Text Cleaning:** Formatting categorical variables (e.g., `unit_type`, `agent`) for consistency.
4. **Calculated Fields:** Creating new business-relevant metrics (`payment_years`, `down_payment_pct`).

In [31]:
# Load the consolidated master dataset into a pandas dataframe for analysis
df = pd.read_csv("all_sales.csv")

# Preview the dataframe to inspect its structure, columns, and initial rows
df

,sale_id,sale_date,customer_id,project_id,unit_type,unit_price,discount,final_price,payment_plan,down_payment,channel,agent,status
0,S2023010000000,2023-01-14,CUST_22585,PRJ_30,3BR,6691492,100000,6591492,8Y,938086.13,Direct,Mona Adel,Pending
1,S2023010000001,2023-01-17,CUST_23621,PRJ_19,Studio,2846816,100000,2746816,Cash,313545.17,Broker,Sara Khaled,Canceled
2,S2023010000002,2023-01-19,CUST_12281,PRJ_4,Villa,1357382,0,1357382,8Y,196379.95,Direct,Mona Adel,Pending
3,S2023010000003,2023-01-11,CUST_8266,PRJ_18,2BR,2363226,100000,2263226,Cash,554752.04,Online,Omar Tarek,Completed
4,S2023010000004,2023-01-18,CUST_14652,PRJ_34,3BR,5212700,0,5212700,5Y,1536354.55,Direct,Youssef Samy,Pending
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1079995,S2025120029995,2025-12-21,CUST_6350,PRJ_10,Studio,8435479,50000,8385479,8Y,2133698.61,Online,Omar Tarek,Completed
1079996,S2025120029996,2025-12-25,CUST_9482,PRJ_7,3BR,1473538,150000,1323538,5Y,376313.27,Online,Heba Mostafa,Canceled
1079997,S2025120029997,2025-12-12,CUST_12868,PRJ_9,Villa,6203054,100000,6103054,Cash,1012280.01,Direct,Heba Mostafa,Completed
1079998,S2025120029998,2025-12-22,CUST_5354,PRJ_24,3BR,2953056,0,2953056,Cash,737956.47,Broker,Ahmed Hassan,Completed
1079999,S2025120029999,2025-12-04,CUST_24896,PRJ_30,3BR,4695991,150000,4545991,5Y,975350.47,Online,Sara Khaled,Completed

In [32]:
# Display a concise summary of the dataframe to inspect data types and identify any missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1080000 entries, 0 to 1079999
Data columns (total 13 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   sale_id       1080000 non-null  object
 1   sale_date     1080000 non-null  object
 2   customer_id   1080000 non-null  object
 3   project_id    1080000 non-null  object
 4   unit_type     1080000 non-null  object
 5   unit_price    1080000 non-null  int64
 6   discount      1080000 non-null  int64
 7   final_price   1080000 non-null  int64
 8   payment_plan  1080000 non-null  object
 9   down_payment  1080000 non-null  float64
 10  channel       1080000 non-null  object
 11  agent         1080000 non-null  object
 12  status        1080000 non-null  object
dtypes: float64(1), int64(3), object(9)
memory usage: 107.1+ MB

In [33]:
# Count the total number of duplicate 'sale_id' values
# This validation step ensures each transaction is unique and prevents double-counting in our analysis
df['sale_id'].duplicated().sum()

np.int64(0)

In [34]:
# Convert the 'sale_date' column to proper datetime objects
df['sale_date'] = pd.to_datetime(df['sale_date'])

# Extract specific temporal features (year and numeric month) 
df['year'] = df['sale_date'].dt.year
df['month'] = df['sale_date'].dt.month

# Extract the categorical month name to enhance readability and label clarity in future visualizations
df['month_name'] = df['sale_date'].dt.month_name()
df.head()

,sale_id,sale_date,customer_id,project_id,unit_type,unit_price,discount,final_price,payment_plan,down_payment,channel,agent,status,year,month,month_name
0,S2023010000000,2023-01-14,CUST_22585,PRJ_30,3BR,6691492,100000,6591492,8Y,938086.13,Direct,Mona Adel,Pending,2023,1,January
1,S2023010000001,2023-01-17,CUST_23621,PRJ_19,Studio,2846816,100000,2746816,Cash,313545.17,Broker,Sara Khaled,Canceled,2023,1,January
2,S2023010000002,2023-01-19,CUST_12281,PRJ_4,Villa,1357382,0,1357382,8Y,196379.95,Direct,Mona Adel,Pending,2023,1,January
3,S2023010000003,2023-01-11,CUST_8266,PRJ_18,2BR,2363226,100000,2263226,Cash,554752.04,Online,Omar Tarek,Completed,2023,1,January
4,S2023010000004,2023-01-18,CUST_14652,PRJ_34,3BR,5212700,0,5212700,5Y,1536354.55,Direct,Youssef Samy,Pending,2023,1,January

In [35]:
# Define categorical text columns that require standardization
text_cols = ['unit_type', 'payment_plan', 'channel', 'agent', 'status']

# Loop through each column to apply consistent text formatting
for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

In [36]:
# Inspect the unique values within the 'payment_plan' column
df['payment_plan'].unique()

array(['8Y', 'Cash', '5Y'], dtype=object)

In [37]:
# Transform the categorical 'payment_plan' into a quantitative 'payment_years' feature
df['payment_years'] = (
    df['payment_plan']
      .replace({'Cash': '0'})
      .str.replace('Y', '', regex=False)
      .astype(int)
)
df

,sale_id,sale_date,customer_id,project_id,unit_type,unit_price,discount,final_price,payment_plan,down_payment,channel,agent,status,year,month,month_name,payment_years
0,S2023010000000,2023-01-14,CUST_22585,PRJ_30,3Br,6691492,100000,6591492,8Y,938086.13,Direct,Mona Adel,Pending,2023,1,January,8
1,S2023010000001,2023-01-17,CUST_23621,PRJ_19,Studio,2846816,100000,2746816,Cash,313545.17,Broker,Sara Khaled,Canceled,2023,1,January,0
2,S2023010000002,2023-01-19,CUST_12281,PRJ_4,Villa,1357382,0,1357382,8Y,196379.95,Direct,Mona Adel,Pending,2023,1,January,8
3,S2023010000003,2023-01-11,CUST_8266,PRJ_18,2Br,2363226,100000,2263226,Cash,554752.04,Online,Omar Tarek,Completed,2023,1,January,0
4,S2023010000004,2023-01-18,CUST_14652,PRJ_34,3Br,5212700,0,5212700,5Y,1536354.55,Direct,Youssef Samy,Pending,2023,1,January,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1079995,S2025120029995,2025-12-21,CUST_6350,PRJ_10,Studio,8435479,50000,8385479,8Y,2133698.61,Online,Omar Tarek,Completed,2025,12,December,8
1079996,S2025120029996,2025-12-25,CUST_9482,PRJ_7,3Br,1473538,150000,1323538,5Y,376313.27,Online,Heba Mostafa,Canceled,2025,12,December,5
1079997,S2025120029997,2025-12-12,CUST_12868,PRJ_9,Villa,6203054,100000,6103054,Cash,1012280.01,Direct,Heba Mostafa,Completed,2025,12,December,0
1079998,S2025120029998,2025-12-22,CUST_5354,PRJ_24,3Br,2953056,0,2953056,Cash,737956.47,Broker,Ahmed Hassan,Completed,2025,12,December,0
1079999,S2025120029999,2025-12-04,CUST_24896,PRJ_30,3Br,4695991,150000,4545991,5Y,975350.47,Online,Sara Khaled,Completed,2025,12,December,5

In [38]:
# Calculate the down payment percentage relative to the total unit price
df['down_payment_pct'] = (df['down_payment'] / df['unit_price']) * 100
df

,sale_id,sale_date,customer_id,project_id,unit_type,unit_price,discount,final_price,payment_plan,down_payment,channel,agent,status,year,month,month_name,payment_years,down_payment_pct
0,S2023010000000,2023-01-14,CUST_22585,PRJ_30,3Br,6691492,100000,6591492,8Y,938086.13,Direct,Mona Adel,Pending,2023,1,January,8,14.019088
1,S2023010000001,2023-01-17,CUST_23621,PRJ_19,Studio,2846816,100000,2746816,Cash,313545.17,Broker,Sara Khaled,Canceled,2023,1,January,0,11.013890
2,S2023010000002,2023-01-19,CUST_12281,PRJ_4,Villa,1357382,0,1357382,8Y,196379.95,Direct,Mona Adel,Pending,2023,1,January,8,14.467552
3,S2023010000003,2023-01-11,CUST_8266,PRJ_18,2Br,2363226,100000,2263226,Cash,554752.04,Online,Omar Tarek,Completed,2023,1,January,0,23.474354
4,S2023010000004,2023-01-18,CUST_14652,PRJ_34,3Br,5212700,0,5212700,5Y,1536354.55,Direct,Youssef Samy,Pending,2023,1,January,5,29.473297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1079995,S2025120029995,2025-12-21,CUST_6350,PRJ_10,Studio,8435479,50000,8385479,8Y,2133698.61,Online,Omar Tarek,Completed,2025,12,December,8,25.294338
1079996,S2025120029996,2025-12-25,CUST_9482,PRJ_7,3Br,1473538,150000,1323538,5Y,376313.27,Online,Heba Mostafa,Canceled,2025,12,December,5,25.538077
1079997,S2025120029997,2025-12-12,CUST_12868,PRJ_9,Villa,6203054,100000,6103054,Cash,1012280.01,Direct,Heba Mostafa,Completed,2025,12,December,0,16.319058
1079998,S2025120029998,2025-12-22,CUST_5354,PRJ_24,3Br,2953056,0,2953056,Cash,737956.47,Broker,Ahmed Hassan,Completed,2025,12,December,0,24.989586
1079999,S2025120029999,2025-12-04,CUST_24896,PRJ_30,3Br,4695991,150000,4545991,5Y,975350.47,Online,Sara Khaled,Completed,2025,12,December,5,20.769854

In [39]:
# Export the fully cleaned and engineered dataset to a new CSV file
df.to_csv("sales_cleaned.csv", index=False)

## Phase 3: Secondary Dataset Ingestion & Dimension Cleaning (Projects Data)

This phase focuses on ensuring structural integrity, removing logical data anomalies, and performing feature engineering to segment projects by market value and lifecycle status.

**Key Objectives for this Phase:**
* **Dimension Profiling:** Ingesting the Excel sheet and validating that the primary key (`project_id`) is strictly unique to support accurate data relationships.
* **Text Uniformity:** Standardizing text fields (Location, Developer, Project Type) to ensure consistent grouping and seamless filtering.
* **Logical Validation & Filtering:** Eliminating operational anomalies, such as negative unit inventories or inverted pricing boundaries.
* **Advanced Feature Engineering:**
  * Deriving descriptive metrics: `price_range` and `avg_price`.
  * Implementing **Data Segmentation** (`price_category`) to establish clean pricing tiers (Low, Medium, High) for executive reporting.
  * Standardizing project status into a unified **Business Taxonomy** (`status`) to streamline dashboard visualization.

In [40]:
# 1) Load the supplementary projects dataset from an Excel file
# Explicitly targeting the "projects.csv" sheet ensures we extract the exact data required for this analysis phase
df = pd.read_excel(
    "projects.xlsx",
    sheet_name="projects.csv"
)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   project_id     40 non-null     object
 1   project_name   40 non-null     object
 2   location       40 non-null     object
 3   developer      40 non-null     object
 4   project_type   40 non-null     object
 5   start_price    40 non-null     int64
 6   max_price      40 non-null     int64
 7   units_count    40 non-null     int64
 8   delivery_year  40 non-null     int64
 9   status         40 non-null     object
dtypes: int64(4), object(6)
memory usage: 3.3+ KB

In [42]:
df.head()

,project_id,project_name,location,developer,project_type,start_price,max_price,units_count,delivery_year,status
0,PRJ_1,Project 1,Nasr City,Palm Hills,Residential,2190024,6394126,195,2025,Ready
1,PRJ_2,Project 2,Mansoura,Tatweer Misr,Mixed Use,1747817,3771744,586,2027,Launched
2,PRJ_3,Project 3,Mansoura,Tatweer Misr,Residential,2038948,8703726,879,2027,Ready
3,PRJ_4,Project 4,October,SODIC,Residential,2517796,5379090,289,2028,Ready
4,PRJ_5,Project 5,Sohag,Emaar,Mixed Use,1305200,8564465,176,2026,Launched

In [43]:
# 2) Count the total number of duplicate 'project_id' values
df['project_id'].duplicated().sum()

np.int64(0)

In [44]:
df.select_dtypes(include=object)

,project_id,project_name,location,developer,project_type,status
0,PRJ_1,Project 1,Nasr City,Palm Hills,Residential,Ready
1,PRJ_2,Project 2,Mansoura,Tatweer Misr,Mixed Use,Launched
2,PRJ_3,Project 3,Mansoura,Tatweer Misr,Residential,Ready
3,PRJ_4,Project 4,October,SODIC,Residential,Ready
4,PRJ_5,Project 5,Sohag,Emaar,Mixed Use,Launched
5,PRJ_6,Project 6,Maadi,Ora Developers,Mixed Use,Ready
6,PRJ_7,Project 7,North Coast,Mountain View,Mixed Use,Launched
7,PRJ_8,Project 8,Zagazig,Ora Developers,Commercial,Ready
8,PRJ_9,Project 9,North Coast,SODIC,Administrative,Launched
9,PRJ_10,Project 10,New Cairo,Hassan Allam,Mixed Use,Ready
10,PRJ_11,Project 11,Hurghada,Palm Hills,Administrative,Ready
11,PRJ_12,Project 12,New Capital,City Edge,Commercial,Launched
12,PRJ_13,Project 13,Ismailia,Ora Developers,Mixed Use,Launched
13,PRJ_14,Project 14,Hurghada,Hassan Allam,Administrative,Ready
14,PRJ_15,Project 15,Zagazig,Mabany Edris,Residential,Launched
15,PRJ_16,Project 16,Assiut,Mabany Edris,Residential,Launched
16,PRJ_17,Project 17,Portsaid,Ora Developers,Commercial,Launched
17,PRJ_18,Project 18,Nasr City,City Edge,Administrative,Under Construction
18,PRJ_19,Project 19,Maadi,Palm Hills,Residential,Ready
19,PRJ_20,Project 20,Smouha,Misr Italia,Administrative,Under Construction
20,PRJ_21,Project 21,Zagazig,Palm Hills,Mixed Use,Launched
21,PRJ_22,Project 22,Assiut,Palm Hills,Commercial,Ready
22,PRJ_23,Project 23,Zagazig,Mabany Edris,Residential,Launched
23,PRJ_24,Project 24,Zagazig,Misr Italia,Administrative,Launched
24,PRJ_25,Project 25,Smouha,Ora Developers,Administrative,Ready
25,PRJ_26,Project 26,October,Palm Hills,Residential,Ready
26,PRJ_27,Project 27,New Cairo,Ora Developers,Residential,Launched
27,PRJ_28,Project 28,Nasr City,Misr Italia,Administrative,Under Construction
28,PRJ_29,Project 29,New Cairo,Mabany Edris,Commercial,Ready
29,PRJ_30,Project 30,Ismailia,City Edge,Residential,Launched
30,PRJ_31,Project 31,Mansoura,Misr Italia,Administrative,Ready
31,PRJ_32,Project 32,New Cairo,Mabany Edris,Administrative,Ready
32,PRJ_33,Project 33,New Cairo,City Edge,Mixed Use,Under Construction
33,PRJ_34,Project 34,Zagazig,Palm Hills,Residential,Under Construction
34,PRJ_35,Project 35,Maadi,Ora Developers,Administrative,Ready
35,PRJ_36,Project 36,Assiut,Misr Italia,Residential,Under Construction
36,PRJ_37,Project 37,Assiut,SODIC,Commercial,Launched
37,PRJ_38,Project 38,New Cairo,Mountain View,Mixed Use,Launched
38,PRJ_39,Project 39,Sohag,Mountain View,Commercial,Ready
39,PRJ_40,Project 40,Sohag,City Edge,Administrative,Launched

In [45]:
# 3) Clean all text columns
# Define categorical text columns within the projects dataset that require standardization
text_cols = [
    'project_name', 'location',
    'developer', 'project_type', 'status']

for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

df.head()

,project_id,project_name,location,developer,project_type,start_price,max_price,units_count,delivery_year,status
0,PRJ_1,Project 1,Nasr City,Palm Hills,Residential,2190024,6394126,195,2025,Ready
1,PRJ_2,Project 2,Mansoura,Tatweer Misr,Mixed Use,1747817,3771744,586,2027,Launched
2,PRJ_3,Project 3,Mansoura,Tatweer Misr,Residential,2038948,8703726,879,2027,Ready
3,PRJ_4,Project 4,October,Sodic,Residential,2517796,5379090,289,2028,Ready
4,PRJ_5,Project 5,Sohag,Emaar,Mixed Use,1305200,8564465,176,2026,Launched

In [46]:
# 4) Calculate the 'price_range' by finding the difference between the maximum and starting prices

df['price_range'] = df['max_price'] - df['start_price']
df.head()

,project_id,project_name,location,developer,project_type,start_price,max_price,units_count,delivery_year,status,price_range
0,PRJ_1,Project 1,Nasr City,Palm Hills,Residential,2190024,6394126,195,2025,Ready,4204102
1,PRJ_2,Project 2,Mansoura,Tatweer Misr,Mixed Use,1747817,3771744,586,2027,Launched,2023927
2,PRJ_3,Project 3,Mansoura,Tatweer Misr,Residential,2038948,8703726,879,2027,Ready,6664778
3,PRJ_4,Project 4,October,Sodic,Residential,2517796,5379090,289,2028,Ready,2861294
4,PRJ_5,Project 5,Sohag,Emaar,Mixed Use,1305200,8564465,176,2026,Launched,7259265

In [47]:
#5) Calculate the 'avg_price' to establish a standardized valuation baseline for each project

df['avg_price'] = (df['max_price'] + df['start_price']) / 2
df.head()

,project_id,project_name,location,developer,project_type,start_price,max_price,units_count,delivery_year,status,price_range,avg_price
0,PRJ_1,Project 1,Nasr City,Palm Hills,Residential,2190024,6394126,195,2025,Ready,4204102,4292075.0
1,PRJ_2,Project 2,Mansoura,Tatweer Misr,Mixed Use,1747817,3771744,586,2027,Launched,2023927,2759780.5
2,PRJ_3,Project 3,Mansoura,Tatweer Misr,Residential,2038948,8703726,879,2027,Ready,6664778,5371337.0
3,PRJ_4,Project 4,October,Sodic,Residential,2517796,5379090,289,2028,Ready,2861294,3948443.0
4,PRJ_5,Project 5,Sohag,Emaar,Mixed Use,1305200,8564465,176,2026,Launched,7259265,4934832.5

In [48]:
# 6) Filter out anomalous records where the starting price exceeds the maximum price

df = df[df['max_price'] >= df['start_price']]
df.head()

,project_id,project_name,location,developer,project_type,start_price,max_price,units_count,delivery_year,status,price_range,avg_price
0,PRJ_1,Project 1,Nasr City,Palm Hills,Residential,2190024,6394126,195,2025,Ready,4204102,4292075.0
1,PRJ_2,Project 2,Mansoura,Tatweer Misr,Mixed Use,1747817,3771744,586,2027,Launched,2023927,2759780.5
2,PRJ_3,Project 3,Mansoura,Tatweer Misr,Residential,2038948,8703726,879,2027,Ready,6664778,5371337.0
3,PRJ_4,Project 4,October,Sodic,Residential,2517796,5379090,289,2028,Ready,2861294,3948443.0
4,PRJ_5,Project 5,Sohag,Emaar,Mixed Use,1305200,8564465,176,2026,Launched,7259265,4934832.5

In [49]:
# 7) Filter out projects with zero or negative unit counts
df = df[df['units_count'] > 0]
df.head()

,project_id,project_name,location,developer,project_type,start_price,max_price,units_count,delivery_year,status,price_range,avg_price
0,PRJ_1,Project 1,Nasr City,Palm Hills,Residential,2190024,6394126,195,2025,Ready,4204102,4292075.0
1,PRJ_2,Project 2,Mansoura,Tatweer Misr,Mixed Use,1747817,3771744,586,2027,Launched,2023927,2759780.5
2,PRJ_3,Project 3,Mansoura,Tatweer Misr,Residential,2038948,8703726,879,2027,Ready,6664778,5371337.0
3,PRJ_4,Project 4,October,Sodic,Residential,2517796,5379090,289,2028,Ready,2861294,3948443.0
4,PRJ_5,Project 5,Sohag,Emaar,Mixed Use,1305200,8564465,176,2026,Launched,7259265,4934832.5

In [50]:
# 8) Segment projects into distinct pricing tiers based on their average price

df['price_category'] = pd.cut(
    df['avg_price'],
    bins=[0, 2000000, 5000000, 10000000],
    labels=['Low', 'Medium', 'High']
)
df.head()

,project_id,project_name,location,developer,project_type,start_price,max_price,units_count,delivery_year,status,price_range,avg_price,price_category
0,PRJ_1,Project 1,Nasr City,Palm Hills,Residential,2190024,6394126,195,2025,Ready,4204102,4292075.0,Medium
1,PRJ_2,Project 2,Mansoura,Tatweer Misr,Mixed Use,1747817,3771744,586,2027,Launched,2023927,2759780.5,Medium
2,PRJ_3,Project 3,Mansoura,Tatweer Misr,Residential,2038948,8703726,879,2027,Ready,6664778,5371337.0,High
3,PRJ_4,Project 4,October,Sodic,Residential,2517796,5379090,289,2028,Ready,2861294,3948443.0,Medium
4,PRJ_5,Project 5,Sohag,Emaar,Mixed Use,1305200,8564465,176,2026,Launched,7259265,4934832.5,Medium

In [51]:
df['status'].unique()

array(['Ready', 'Launched', 'Under Construction'], dtype=object)

In [52]:
# 9) Status Cleaning & Standardization
# Consolidate project status categories into a standardized business taxonomy

df['status'] = df['status'].replace({
    'Launched': 'Under Development',
    'Ready': 'Delivered'
})

# Preview the dataframe to confirm the status values have been successfully unified
df.head()

,project_id,project_name,location,developer,project_type,start_price,max_price,units_count,delivery_year,status,price_range,avg_price,price_category
0,PRJ_1,Project 1,Nasr City,Palm Hills,Residential,2190024,6394126,195,2025,Delivered,4204102,4292075.0,Medium
1,PRJ_2,Project 2,Mansoura,Tatweer Misr,Mixed Use,1747817,3771744,586,2027,Under Development,2023927,2759780.5,Medium
2,PRJ_3,Project 3,Mansoura,Tatweer Misr,Residential,2038948,8703726,879,2027,Delivered,6664778,5371337.0,High
3,PRJ_4,Project 4,October,Sodic,Residential,2517796,5379090,289,2028,Delivered,2861294,3948443.0,Medium
4,PRJ_5,Project 5,Sohag,Emaar,Mixed Use,1305200,8564465,176,2026,Under Development,7259265,4934832.5,Medium

In [53]:
df['status'].unique()

array(['Delivered', 'Under Development', 'Under Construction'],
      dtype=object)

In [54]:
# 10) Export the fully cleaned and engineered projects dimension table to a new CSV file
df.to_csv("projects_cleaned.csv", index=False)

## Phase 4: Customer Dimension Cleaning & Comprehensive Standardization

This phase focuses on ingesting and standardizing the customer dimension table. The objective is to ensure structural integrity, clean Personally Identifiable Information (PII), translate categorical variables, and perform advanced geospatial and temporal feature engineering to support seamless dashboard filtering.

**Key Objectives for this Phase:**
* **Dimension Profiling:** Ingesting the dataset and validating the uniqueness of the primary key (`customer_id`) to maintain robust dimension-to-fact relationships.
* **PII & Text Uniformity:** 
  * Applying defensive string formatting (strip, title, lower) to text columns and emails.
  * Utilizing Regular Expressions (Regex `\D`) to extract and standardize numeric phone values.
* **Categorical Translation & Taxonomy:** Standardizing bilingual categorical fields (`customer_type`, `lead_source`) by translating Arabic entries into a unified English taxonomy, preventing encoding issues in downstream BI tools.
* **Temporal Feature Engineering:** Converting raw `created_at` strings into precise datetime objects, and extracting distinct temporal dimensions (`created_year`, `created_month`) to enable time-series analysis and storytelling.
* **Advanced Geospatial Normalization:** Implementing hierarchical tuple mapping to transform unstructured, messy address strings into clean, standardized `city` and `governorate` columns, effectively reducing noise for high-level spatial analysis.

In [55]:
# 1) Load the third foundational dataset: The Customers Dimension Table

df = pd.read_excel(
    "customers_realistic_address.xlsx",
    sheet_name="customers_realistic_address.csv"
)
df.head()

,customer_id,full_name,phone,email,address,customer_type,lead_source,budget_range,created_at,sales_agent,segment
0,CUST_1,Customer 1,1077415596,customer1@mail.com,"الجيزة, SheikhZayed, Youth Housing, عمارة 12",Individual,Referral,3-5M,2025-05-27,Mohamed,Normal
1,CUST_2,Customer 2,1020857153,customer2@mail.com,"الدقهلية, Mansoura, Portsaid, عمارة 64",شركه,Event,5M+,2024-05-02,Ahmed,Normal
2,CUST_3,Customer 3,1087052530,customer3@mail.com,"Assiut, Assiut East, El Geish, عمارة 23",Individual,واتساب,2-3M,2023-06-30,Ahmed,New
3,CUST_4,Customer 4,1070589979,customer4@mail.com,"Assiut, Assiut East, Helaly, building 80",فرد,واتساب,1-2M,2025-06-22,Ali,VIP
4,CUST_5,Customer 5,1081852995,customer5@mail.com,"اسيوط, AssiutEast, El Geish, B60",Company,Referral,3-5M,2025-07-17,Mohamed,Normal

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    30000 non-null  object
 1   full_name      30000 non-null  object
 2   phone          30000 non-null  int64
 3   email          30000 non-null  object
 4   address        30000 non-null  object
 5   customer_type  30000 non-null  object
 6   lead_source    30000 non-null  object
 7   budget_range   30000 non-null  object
 8   created_at     30000 non-null  datetime64[ns]
 9   sales_agent    30000 non-null  object
 10  segment        30000 non-null  object
dtypes: datetime64[ns](1), int64(1), object(9)
memory usage: 2.5+ MB

In [57]:
# 2) Count the total number of duplicate 'customer_id' values
df['customer_id'].duplicated().sum()

np.int64(0)

In [58]:
df.select_dtypes(include=object)

,customer_id,full_name,email,address,customer_type,lead_source,budget_range,sales_agent,segment
0,CUST_1,Customer 1,customer1@mail.com,"الجيزة, SheikhZayed, Youth Housing, عمارة 12",Individual,Referral,3-5M,Mohamed,Normal
1,CUST_2,Customer 2,customer2@mail.com,"الدقهلية, Mansoura, Portsaid, عمارة 64",شركه,Event,5M+,Ahmed,Normal
2,CUST_3,Customer 3,customer3@mail.com,"Assiut, Assiut East, El Geish, عمارة 23",Individual,واتساب,2-3M,Ahmed,New
3,CUST_4,Customer 4,customer4@mail.com,"Assiut, Assiut East, Helaly, building 80",فرد,واتساب,1-2M,Ali,VIP
4,CUST_5,Customer 5,customer5@mail.com,"اسيوط, AssiutEast, El Geish, B60",Company,Referral,3-5M,Mohamed,Normal
...,...,...,...,...,...,...,...,...,...
29995,CUST_29996,Customer 29996,customer29996@mail.com,"Dakahlia, Mansoura, Gomhoria, building 65",Company,Event,1-2M,Sara,Normal
29996,CUST_29997,Customer 29997,customer29997@mail.com,"الجيزه, Dokki, Mosadak, B10",Individual,Facebook,3-5M,Ali,Normal
29997,CUST_29998,Customer 29998,customer29998@mail.com,"Suez, Arbeen, El Geish, B62",Company,Call,1-2M,Ahmed,Normal
29998,CUST_29999,Customer 29999,customer29999@mail.com,"الجيزه, Mohandseen, Gameat El Dowal, building 59",فرد,Facebook,5M+,Ahmed,VIP
29999,CUST_30000,Customer 30000,customer30000@mail.com,"الجيزة, Mohandseen, Lebanon, B10",Company,Referral,5M+,Ali,VIP

In [59]:
# 3) Clean text columns
# Define categorical text columns within the projects dataset that require standardization
text_cols = [
    'full_name', 'address',
    'sales_agent', 'segment']

for col in text_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

df.head()

,customer_id,full_name,phone,email,address,customer_type,lead_source,budget_range,created_at,sales_agent,segment
0,CUST_1,Customer 1,1077415596,customer1@mail.com,"الجيزة, Sheikhzayed, Youth Housing, عمارة 12",Individual,Referral,3-5M,2025-05-27,Mohamed,Normal
1,CUST_2,Customer 2,1020857153,customer2@mail.com,"الدقهلية, Mansoura, Portsaid, عمارة 64",شركه,Event,5M+,2024-05-02,Ahmed,Normal
2,CUST_3,Customer 3,1087052530,customer3@mail.com,"Assiut, Assiut East, El Geish, عمارة 23",Individual,واتساب,2-3M,2023-06-30,Ahmed,New
3,CUST_4,Customer 4,1070589979,customer4@mail.com,"Assiut, Assiut East, Helaly, Building 80",فرد,واتساب,1-2M,2025-06-22,Ali,Vip
4,CUST_5,Customer 5,1081852995,customer5@mail.com,"اسيوط, Assiuteast, El Geish, B60",Company,Referral,3-5M,2025-07-17,Mohamed,Normal

In [60]:
# 4) Email Cleaning
df['email'] = df['email'].astype(str).str.strip().str.lower()

In [61]:
# 5) Clean the 'phone' column using Regular Expressions (Regex)
# The '\D' pattern matches any non-digit character (e.g., spaces, dashes, parentheses) and removes it

df['phone'] = df['phone'].astype(str).str.replace(r'\D', '', regex=True)

In [62]:
df['customer_type'].unique()

array(['Individual', 'شركه', 'فرد', 'Company'], dtype=object)

In [63]:
# 6) Standardize the 'customer_type' column by translating Arabic values to English

df['customer_type'] = df['customer_type'].replace({
    'فرد': 'Individual',
    'شركه': 'Company'
})

In [64]:
# 7) Apply string formatting to the 'customer_type' column as a defensive measure
df['customer_type'] = df['customer_type'].astype(str).str.strip().str.title()
df.head()

,customer_id,full_name,phone,email,address,customer_type,lead_source,budget_range,created_at,sales_agent,segment
0,CUST_1,Customer 1,1077415596,customer1@mail.com,"الجيزة, Sheikhzayed, Youth Housing, عمارة 12",Individual,Referral,3-5M,2025-05-27,Mohamed,Normal
1,CUST_2,Customer 2,1020857153,customer2@mail.com,"الدقهلية, Mansoura, Portsaid, عمارة 64",Company,Event,5M+,2024-05-02,Ahmed,Normal
2,CUST_3,Customer 3,1087052530,customer3@mail.com,"Assiut, Assiut East, El Geish, عمارة 23",Individual,واتساب,2-3M,2023-06-30,Ahmed,New
3,CUST_4,Customer 4,1070589979,customer4@mail.com,"Assiut, Assiut East, Helaly, Building 80",Individual,واتساب,1-2M,2025-06-22,Ali,Vip
4,CUST_5,Customer 5,1081852995,customer5@mail.com,"اسيوط, Assiuteast, El Geish, B60",Company,Referral,3-5M,2025-07-17,Mohamed,Normal

In [65]:
df['lead_source'].unique()

array(['Referral', 'Event', 'واتساب', 'Facebook', 'Call'], dtype=object)

In [66]:
# 8) Standardize the 'lead_source' column by translating Arabic entries to English
df['lead_source'] = df['lead_source'].replace({
    'واتساب': 'WhatsApp'
})
df.head()

,customer_id,full_name,phone,email,address,customer_type,lead_source,budget_range,created_at,sales_agent,segment
0,CUST_1,Customer 1,1077415596,customer1@mail.com,"الجيزة, Sheikhzayed, Youth Housing, عمارة 12",Individual,Referral,3-5M,2025-05-27,Mohamed,Normal
1,CUST_2,Customer 2,1020857153,customer2@mail.com,"الدقهلية, Mansoura, Portsaid, عمارة 64",Company,Event,5M+,2024-05-02,Ahmed,Normal
2,CUST_3,Customer 3,1087052530,customer3@mail.com,"Assiut, Assiut East, El Geish, عمارة 23",Individual,WhatsApp,2-3M,2023-06-30,Ahmed,New
3,CUST_4,Customer 4,1070589979,customer4@mail.com,"Assiut, Assiut East, Helaly, Building 80",Individual,WhatsApp,1-2M,2025-06-22,Ali,Vip
4,CUST_5,Customer 5,1081852995,customer5@mail.com,"اسيوط, Assiuteast, El Geish, B60",Company,Referral,3-5M,2025-07-17,Mohamed,Normal

In [67]:
# 9) Apply string formatting to the 'lead_source' column as a defensive measure
df['lead_source'] = df['lead_source'].astype(str).str.strip().str.title()
df.head()

,customer_id,full_name,phone,email,address,customer_type,lead_source,budget_range,created_at,sales_agent,segment
0,CUST_1,Customer 1,1077415596,customer1@mail.com,"الجيزة, Sheikhzayed, Youth Housing, عمارة 12",Individual,Referral,3-5M,2025-05-27,Mohamed,Normal
1,CUST_2,Customer 2,1020857153,customer2@mail.com,"الدقهلية, Mansoura, Portsaid, عمارة 64",Company,Event,5M+,2024-05-02,Ahmed,Normal
2,CUST_3,Customer 3,1087052530,customer3@mail.com,"Assiut, Assiut East, El Geish, عمارة 23",Individual,Whatsapp,2-3M,2023-06-30,Ahmed,New
3,CUST_4,Customer 4,1070589979,customer4@mail.com,"Assiut, Assiut East, Helaly, Building 80",Individual,Whatsapp,1-2M,2025-06-22,Ali,Vip
4,CUST_5,Customer 5,1081852995,customer5@mail.com,"اسيوط, Assiuteast, El Geish, B60",Company,Referral,3-5M,2025-07-17,Mohamed,Normal

In [68]:
# 10) Budget Range Cleaning
df['budget_range'] = df['budget_range'].astype(str).str.strip()

In [69]:
# 11) Temporal Standardization and Feature Extraction
# Convert the 'created_at' column to a proper datetime object 
df['created_at'] = pd.to_datetime(df['created_at'])

# Extract 'created_year' and 'created_month' to enable 
df['created_year'] = df['created_at'].dt.year
df['created_month'] = df['created_at'].dt.month

In [70]:
# .tolist() forces Python to print every single unique value vertically
df['address'].unique().tolist()

['الجيزة, Sheikhzayed, Youth Housing, عمارة 12',
 'الدقهلية, Mansoura, Portsaid, عمارة 64',
 'Assiut, Assiut East, El Geish, عمارة 23',
 'Assiut, Assiut East, Helaly, Building 80',
 'اسيوط, Assiuteast, El Geish, B60',
 'الجيزة, Dokki, Tahrir, عمارة 6',
 'السويس, Arbeen, El Geish, عمارة 24',
 'Suez, Arbeen, Elgeish, Building 53',
 'Alex, Miami, Khaledibnelwalid, Building 20',
 'السويس, Arbeen, Elgeish, Building 97',
 'Suez, Arbeen, Elgeish, عمارة 44',
 'Alex, Miami, Khaled Ibn El Walid, B90',
 'Alex, Smouha, Victoremanuel, عمارة 98',
 'الاسكندريه, Smouha, Victoremanuel, Building 98',
 'Dakahlia, Mansoura, Portsaid, B69',
 'Assiut, Assiuteast, Helaly, Building 93',
 'Dakahlia, Mansoura, Portsaid, Building 20',
 'أسيوط, Assiut East, Helaly, عمارة 98',
 'Giza, Dokki, Tahrir, عمارة 74',
 'Cairo, Maadi, Degla, B51',
 'الإسكندرية, Lauran, Abdelsalamaref, Building 99',
 'الإسكندرية, Smouha, Fawzy Moaz, B27',
 'القاهره, Nasr City, Makram Ebeid, Building 13',
 'الدقهلية, Mansoura, Portsaid, B77',
 'الإسكندرية, Miami, Khaled Ibn El Walid, Building 94',
 'Alex, Smouha, Victoremanuel, Building 118',
 'Suez, Arbeen, El Geish, B6',
 'اسيوط, Assiut East, Helaly, عمارة 23',
 'Assiut, Assiuteast, El Geish, عمارة 36',
 'Suez, Arbeen, Elgeish, عمارة 35',
 'الدقهليه, Mansoura, Gomhoria, Building 37',
 'الجيزه, Sheikhzayed, Beverly Hills, B38',
 'الاسكندريه, Lauran, Abdelsalamaref, Building 29',
 'الدقهلية, Mansoura, Gomhoria, عمارة 10',
 'الدقهلية, Mansoura, Portsaid, Building 24',
 'الاسكندريه, Miami, Khaled Ibn El Walid, B39',
 'Assiut, Assiut East, El Geish, B77',
 'الدقهليه, Mansoura, Portsaid, Building 15',
 'Suez, Arbeen, El Geish, Building 59',
 'الدقهليه, Mansoura, Gomhoria, B62',
 'القاهرة, Heliopolis, Orouba, Building 101',
 'القاهره, Heliopolis, Nozha, عمارة 88',
 'Cairo, New Cairo, South 90, B96',
 'الجيزة, Mohandseen, Lebanon, B87',
 'الإسكندرية, Smouha, Victoremanuel, B65',
 'الإسكندرية, Miami, Khaledibnelwalid, Building 43',
 'Alex, Lauran, Abdelsalamaref, عمارة 89',
 'Cairo, Maadi, Laselky, Building 31',
 'Giza, Sheikhzayed, Beverly Hills, B47',
 'اسيوط, Assiuteast, Helaly, Building 103',
 'Suez, Arbeen, El Geish, B15',
 'اسيوط, Assiut East, El Geish, B12',
 'Alex, Smouha, Fawzy Moaz, B12',
 'Suez, Arbeen, Elgeish, Building 89',
 'الإسكندرية, Lauran, Abdelsalamaref, B46',
 'الدقهليه, Mansoura, Portsaid, B99',
 'Cairo, New Cairo, North 90, عمارة 87',
 'السويس, Arbeen, Elgeish, عمارة 92',
 'Assiut, Assiuteast, Helaly, B10',
 'السويس, Arbeen, El Geish, Building 16',
 'الجيزة, Mohandseen, Gameat El Dowal, Building 61',
 'الدقهليه, Mansoura, Portsaid, B12',
 'السويس, Arbeen, Elgeish, B16',
 'الإسكندرية, Miami, Khaled Ibn El Walid, B2',
 'الجيزة, Sheikhzayed, Beverlyhills, Building 57',
 'الإسكندرية, Smouha, Fawzymoaz, Building 54',
 'القاهره, Nasrcity, Abbaselakkad, Building 20',
 'الإسكندرية, Miami, Khaledibnelwalid, B79',
 'Dakahlia, Mansoura, Portsaid, عمارة 5',
 'Dakahlia, Mansoura, Portsaid, عمارة 85',
 'الدقهلية, Mansoura, Gomhoria, Building 78',
 'Assiut, Assiuteast, Elgeish, Building 52',
 'Alex, Lauran, Abdelsalamaref, B83',
 'القاهره, New Cairo, South 90, Building 65',
 'Suez, Arbeen, El Geish, Building 93',
 'الدقهليه, Mansoura, Gomhoria, عمارة 120',
 'الجيزة, Sheikh Zayed, District1, عمارة 51',
 'الإسكندرية, Miami, Khaled Ibn El Walid, Building 39',
 'Cairo, Nasr City, Makramebeid, عمارة 111',
 'القاهره, Nasrcity, Abbaselakkad, B53',
 'Dakahlia, Mansoura, Gomhoria, B52',
 'الإسكندرية, Smouha, Fawzy Moaz, عمارة 3',
 'Giza, Dokki, Sudan, عمارة 69',
 'Assiut, Assiuteast, Helaly, B69',
 'أسيوط, Assiut East, El Geish, B17',
 'Suez, Arbeen, Elgeish, Building 5',
 'الدقهليه, Mansoura, Gomhoria, B25',
 'الإسكندرية, Smouha, Victoremanuel, Building 68',
 'Cairo, Newcairo, South 90, عمارة 91',
 'الدقهلية, Mansoura, Gomhoria, Building 44',
 'السويس, Arbeen, Elgeish, Building 15',
 'Suez, Arbeen, Elgeish, عمارة 96',
 'Assiut, Assiut East, Helaly, B30',
 'الجيزة, Dokki, Tahrir, B74',
 'Assiut, Assiuteast, El Geish, Building 26',
 'Alex, Lauran, Abdelsalamaref, عمارة 100',
 'Assiut, Assiuteast, Helaly, B55',
 'أسيوط, Assiuteast, Elgeish, عمارة 81',
 'Suez, Arbeen, Elgeish, B35',
 'القاهرة, Maadi, Street 9, Building 111',
 'الجيزة, Sheikhzayed, Youth Housing, عمارة 86',
 'Assiut, Assiut East, Elgeish, B29',
 'Dakahlia, Mansoura, Gomhoria, عمارة 98',
 'Assiut, Assiuteast, Elgeish, عمارة 3',
 'Cairo, Nasr City, Abbas El Akkad, عمارة 8',
 'Assiut, Assiut East, El Geish, B89',
 'الجيزه, Sheikh Zayed, District 1, عمارة 20',
 'السويس, Arbeen, El Geish, B37',
 'القاهرة, New Cairo, 90Thstreet, Building 115',
 'القاهرة, Maadi, Laselky, B72',
 'أسيوط, Assiut East, Helaly, عمارة 4',
 'الجيزه, Sheikh Zayed, Youthhousing, عمارة 65',
 'Giza, Mohandseen, Gameateldowal, عمارة 44',
 'Suez, Arbeen, Elgeish, B2',
 'الجيزه, Dokki, Mosadak, عمارة 40',
 'Alex, Lauran, Abdelsalamaref, B47',
 'الجيزه, Mohandseen, Lebanon, عمارة 27',
 'الدقهليه, Mansoura, Gomhoria, Building 101',
 'Cairo, Nasr City, Makram Ebeid, Building 56',
 'الجيزة, Dokki, Tahrir, B6',
 'Alex, Smouha, Fawzymoaz, Building 69',
 'السويس, Arbeen, El Geish, Building 69',
 'اسيوط, Assiuteast, Helaly, Building 87',
 'Alex, Smouha, Victor Emanuel, Building 38',
 'Giza, Mohandseen, Lebanon, B18',
 'الإسكندرية, Miami, Khaled Ibn El Walid, B115',
 'الجيزة, Mohandseen, Shehab, B47',
 'Giza, Dokki, Tahrir, Building 18',
 'الجيزه, Dokki, Mosadak, عمارة 84',
 'Alex, Smouha, Victoremanuel, عمارة 38',
 'Alex, Smouha, Fawzymoaz, B52',
 'Assiut, Assiut East, Elgeish, Building 102',
 'Alex, Miami, Khaledibnelwalid, Building 18',
 'الجيزه, Sheikhzayed, District 1, عمارة 15',
 'أسيوط, Assiuteast, El Geish, B5',
 'الإسكندرية, Lauran, Abdelsalamaref, عمارة 31',
 'Cairo, New Cairo, 90Thstreet, B84',
 'الاسكندريه, Lauran, Abdelsalamaref, عمارة 70',
 'اسيوط, Assiuteast, Helaly, عمارة 86',
 'القاهرة, Maadi, Laselky, B48',
 'الاسكندريه, Lauran, Abdel Salam Aref, B18',
 'Giza, Dokki, Mosadak, Building 49',
 'القاهرة, Maadi, Degla, عمارة 3',
 'اسيوط, Assiuteast, El Geish, B16',
 'أسيوط, Assiut East, El Geish, B101',
 'Dakahlia, Mansoura, Portsaid, عمارة 99',
 'الدقهلية, Mansoura, Portsaid, B27',
 'Giza, Mohandseen, Gameateldowal, Building 57',
 'الاسكندريه, Lauran, Abdel Salam Aref, عمارة 68',
 'الجيزه, Sheikh Zayed, District 1, Building 1',
 'Suez, Arbeen, El Geish, Building 5',
 'الاسكندريه, Smouha, Fawzymoaz, B54',
 'أسيوط, Assiuteast, El Geish, B24',
 'Giza, Dokki, Sudan, B87',
 'Suez, Arbeen, El Geish, Building 39',
 'القاهره, Heliopolis, Orouba, B58',
 'Cairo, Maadi, Laselky, Building 15',
 'السويس, Arbeen, Elgeish, B118',
 'أسيوط, Assiut East, Elgeish, B108',
 'الجيزة, Sheikhzayed, Beverly Hills, عمارة 22',
 'اسيوط, Assiut East, Helaly, عمارة 77',
 'الجيزة, Sheikh Zayed, Beverly Hills, B20',
 'الدقهلية, Mansoura, Gomhoria, B25',
 'اسيوط, Assiut East, Helaly, Building 56',
 'Assiut, Assiuteast, El Geish, Building 16',
 'الإسكندرية, Lauran, Abdelsalamaref, B60',
 'القاهرة, Heliopolis, Merghany, عمارة 119',
 'Alex, Miami, Khaled Ibn El Walid, B28',
 'الإسكندرية, Smouha, Victor Emanuel, Building 83',
 'الاسكندريه, Smouha, Fawzymoaz, عمارة 80',
 'الجيزة, Mohandseen, Gameat El Dowal, B7',
 'Suez, Arbeen, Elgeish, Building 32',
 'اسيوط, Assiut East, Elgeish, Building 54',
 'الدقهلية, Mansoura, Gomhoria, Building 25',
 'اسيوط, Assiut East, Elgeish, B44',
 'اسيوط, Assiut East, Helaly, عمارة 76',
 'اسيوط, Assiut East, El Geish, Building 75',
 'القاهره, Maadi, Degla, Building 22',
 'الدقهليه, Mansoura, Portsaid, Building 57',
 'Cairo, Heliopolis, Nozha, B6',
 'الجيزه, Dokki, Mosadak, B59',
 'الجيزه, Dokki, Sudan, عمارة 101',
 'أسيوط, Assiuteast, Helaly, عمارة 119',
 'الجيزة, Mohandseen, Gameateldowal, عمارة 12',
 'الدقهلية, Mansoura, Portsaid, Building 44',
 'القاهره, Heliopolis, Orouba, عمارة 30',
 'الإسكندرية, Smouha, Victoremanuel, عمارة 91',
 'Cairo, Heliopolis, Orouba, عمارة 41',
 'الدقهلية, Mansoura, Gomhoria, Building 89',
 'الجيزه, Dokki, Sudan, B42',
 'السويس, Arbeen, El Geish, عمارة 37',
 'الاسكندريه, Lauran, Abdel Salam Aref, B27',
 'Suez, Arbeen, Elgeish, Building 50',
 'القاهرة, Nasrcity, Makram Ebeid, B34',
 'الاسكندريه, Lauran, Abdelsalamaref, عمارة 106',
 'القاهره, Nasr City, Abbaselakkad, Building 28',
 'الدقهلية, Mansoura, Portsaid, Building 100',
 'الجيزه, Sheikhzayed, Beverly Hills, عمارة 54',
 'الجيزه, Sheikh Zayed, Beverlyhills, Building 95',
 'الإسكندرية, Smouha, Victor Emanuel, عمارة 40',
 'أسيوط, Assiuteast, Helaly, B103',
 'الدقهليه, Mansoura, Gomhoria, Building 114',
 'الجيزه, Mohandseen, Gameateldowal, B6',
 'Giza, Sheikhzayed, Youth Housing, عمارة 76',
 'القاهرة, Nasrcity, Abbaselakkad, B63',
 'الجيزه, Dokki, Mosadak, B47',
 'Alex, Lauran, Abdelsalamaref, B27',
 'الجيزه, Dokki, Mosadak, B46',
 'أسيوط, Assiuteast, Helaly, B111',
 'القاهرة, Newcairo, South90, Building 114',
 'القاهرة, Nasrcity, Makram Ebeid, B5',
 'الجيزة, Dokki, Mosadak, B43',
 'Assiut, Assiut East, Elgeish, B95',
 'أسيوط, Assiut East, Helaly, Building 99',
 'Suez, Arbeen, El Geish, عمارة 38',
 'الجيزه, Dokki, Sudan, عمارة 83',
 'الدقهليه, Mansoura, Gomhoria, B67',
 'القاهرة, Maadi, Degla, عمارة 88',
 'الجيزة, Mohandseen, Lebanon, B71',
 'القاهرة, Maadi, Laselky, B80',
 'الجيزه, Dokki, Tahrir, B55',
 'الإسكندرية, Lauran, Abdelsalamaref, Building 114',
 'الدقهلية, Mansoura, Gomhoria, عمارة 37',
 'الدقهليه, Mansoura, Gomhoria, B71',
 'الدقهلية, Mansoura, Gomhoria, Building 30',
 'الجيزه, Mohandseen, Gameateldowal, Building 83',
 'أسيوط, Assiut East, Helaly, عمارة 6',
 'السويس, Arbeen, El Geish, عمارة 90',
 'الجيزه, Mohandseen, Lebanon, عمارة 89',
 'Cairo, Maadi, Degla, عمارة 11',
 'Dakahlia, Mansoura, Portsaid, Building 39',
 'اسيوط, Assiuteast, El Geish, B72',
 'الجيزة, Sheikh Zayed, Beverly Hills, Building 30',
 'القاهره, Heliopolis, Orouba, Building 93',
 'الدقهلية, Mansoura, Gomhoria, B10',
 'أسيوط, Assiut East, Elgeish, Building 103',
 'الاسكندريه, Miami, Khaledibnelwalid, Building 19',
 'Alex, Lauran, Abdelsalamaref, B1',
 'الجيزة, Dokki, Mosadak, Building 11',
 'Alex, Smouha, Victoremanuel, B69',
 'الدقهلية, Mansoura, Gomhoria, B8',
 'الإسكندرية, Lauran, Abdelsalamaref, عمارة 32',
 'Dakahlia, Mansoura, Gomhoria, عمارة 72',
 'القاهرة, Nasr City, Abbaselakkad, Building 19',
 'Giza, Mohandseen, Lebanon, B59',
 'Assiut, Assiuteast, Helaly, عمارة 111',
 'القاهرة, Newcairo, North 90, Building 116',
 'Cairo, Maadi, Degla, B22',
 'Suez, Arbeen, Elgeish, عمارة 23',
 'الاسكندريه, Lauran, Abdelsalamaref, عمارة 46',
 'Assiut, Assiuteast, Helaly, عمارة 14',
 'Dakahlia, Mansoura, Gomhoria, عمارة 91',
 'Assiut, Assiuteast, Helaly, B93',
 'Assiut, Assiuteast, El Geish, Building 19',
 'الاسكندريه, Lauran, Abdel Salam Aref, B37',
 'الدقهليه, Mansoura, Gomhoria, عمارة 14',
 'Cairo, Maadi, Degla, B109',
 'Giza, Dokki, Tahrir, B77',
 'الدقهليه, Mansoura, Portsaid, Building 110',
 'Giza, Dokki, Mosadak, عمارة 37',
 'أسيوط, Assiuteast, Helaly, عمارة 104',
 'القاهرة, Newcairo, North 90, B39',
 'القاهرة, Nasrcity, Makram Ebeid, Building 3',
 'الإسكندرية, Smouha, Fawzymoaz, عمارة 41',
 'الدقهلية, Mansoura, Gomhoria, Building 106',
 'الدقهليه, Mansoura, Portsaid, B96',
 'الاسكندريه, Lauran, Abdel Salam Aref, عمارة 88',
 'Giza, Sheikh Zayed, Youth Housing, B101',
 'Assiut, Assiut East, Helaly, Building 14',
 'الاسكندريه, Miami, Khaled Ibn El Walid, عمارة 99',
 'السويس, Arbeen, Elgeish, عمارة 112',
 'أسيوط, Assiut East, Helaly, B19',
 'القاهره, New Cairo, North 90, عمارة 119',
 'Assiut, Assiuteast, El Geish, عمارة 61',
 'Giza, Mohandseen, Shehab, Building 35',
 'الجيزه, Sheikhzayed, District 1, Building 9',
 'القاهره, Newcairo, South90, عمارة 24',
 'السويس, Arbeen, Elgeish, عمارة 18',
 'السويس, Arbeen, Elgeish, B81',
 'Giza, Dokki, Tahrir, Building 111',
 'Dakahlia, Mansoura, Gomhoria, Building 63',
 'الدقهليه, Mansoura, Gomhoria, عمارة 114',
 'Assiut, Assiut East, El Geish, Building 41',
 'الجيزة, Sheikhzayed, District1, عمارة 64',
 'القاهره, Newcairo, South 90, B15',
 'Alex, Lauran, Abdelsalamaref, Building 113',
 'القاهرة, Newcairo, 90Thstreet, Building 3',
 'Dakahlia, Mansoura, Portsaid, عمارة 58',
 'القاهره, Heliopolis, Merghany, عمارة 103',
 'Dakahlia, Mansoura, Gomhoria, Building 119',
 'Assiut, Assiut East, El Geish, عمارة 90',
 'Suez, Arbeen, Elgeish, Building 23',
 'Giza, Sheikhzayed, Beverlyhills, B74',
 'Alex, Lauran, Abdel Salam Aref, B79',
 'Dakahlia, Mansoura, Gomhoria, B75',
 'اسيوط, Assiuteast, El Geish, عمارة 109',
 'القاهرة, Heliopolis, Orouba, عمارة 45',
 'السويس, Arbeen, El Geish, Building 29',
 'Dakahlia, Mansoura, Gomhoria, Building 54',
 'السويس, Arbeen, El Geish, عمارة 77',
 'Cairo, Heliopolis, Orouba, عمارة 112',
 'Dakahlia, Mansoura, Gomhoria, عمارة 30',
 'أسيوط, Assiuteast, Helaly, B25',
 'اسيوط, Assiut East, Elgeish, عمارة 14',
 'أسيوط, Assiuteast, Elgeish, B93',
 'Alex, Smouha, Fawzy Moaz, عمارة 21',
 'السويس, Arbeen, Elgeish, B116',
 'Alex, Lauran, Abdelsalamaref, عمارة 96',
 'Cairo, Maadi, Street9, B85',
 'الدقهلية, Mansoura, Portsaid, Building 116',
 'الجيزة, Sheikhzayed, District 1, Building 64',
 'Dakahlia, Mansoura, Gomhoria, Building 116',
 'Alex, Miami, Khaled Ibn El Walid, عمارة 96',
 'السويس, Arbeen, El Geish, B8',
 'القاهرة, Nasr City, Makramebeid, B47',
 'القاهرة, Nasrcity, Makram Ebeid, عمارة 68',
 'الدقهلية, Mansoura, Portsaid, Building 118',
 'الدقهليه, Mansoura, Portsaid, B57',
 'Giza, Sheikh Zayed, District1, عمارة 108',
 'اسيوط, Assiuteast, Helaly, B48',
 'Giza, Dokki, Mosadak, Building 15',
 'الدقهلية, Mansoura, Portsaid, Building 22',
 'الدقهلية, Mansoura, Gomhoria, Building 6',
 'Suez, Arbeen, El Geish, عمارة 89',
 'القاهره, New Cairo, 90Th Street, B103',
 'الاسكندريه, Smouha, Victoremanuel, Building 92',
 'Giza, Mohandseen, Gameat El Dowal, B112',
 'Giza, Mohandseen, Gameat El Dowal, Building 62',
 'Suez, Arbeen, El Geish, B43',
 'الجيزه, Mohandseen, Shehab, عمارة 114',
 'الدقهليه, Mansoura, Gomhoria, عمارة 1',
 'Cairo, Heliopolis, Merghany, B70',
 'Assiut, Assiut East, El Geish, B36',
 'الاسكندريه, Lauran, Abdelsalamaref, Building 101',
 'Alex, Smouha, Victoremanuel, B12',
 'Suez, Arbeen, El Geish, Building 32',
 'القاهرة, Maadi, Laselky, Building 73',
 'Giza, Sheikhzayed, Beverlyhills, عمارة 75',
 'Alex, Miami, Khaled Ibn El Walid, عمارة 52',
 'أسيوط, Assiuteast, Elgeish, عمارة 113',
 'السويس, Arbeen, El Geish, عمارة 39',
 'Dakahlia, Mansoura, Portsaid, Building 97',
 'Giza, Dokki, Tahrir, عمارة 49',
 'Dakahlia, Mansoura, Gomhoria, B112',
 'Dakahlia, Mansoura, Portsaid, Building 105',
 'Cairo, Heliopolis, Orouba, B74',
 'القاهره, Maadi, Street 9, عمارة 63',
 'اسيوط, Assiut East, Elgeish, B102',
 'Assiut, Assiuteast, Helaly, Building 92',
 'Suez, Arbeen, Elgeish, Building 12',
 'Suez, Arbeen, El Geish, عمارة 37',
 'القاهره, Maadi, Street 9, B36',
 'Dakahlia, Mansoura, Portsaid, عمارة 25',
 'Giza, Dokki, Mosadak, Building 94',
 'Suez, Arbeen, El Geish, عمارة 62',
 'الإسكندرية, Miami, Khaled Ibn El Walid, عمارة 57',
 'السويس, Arbeen, Elgeish, Building 44',
 'اسيوط, Assiuteast, Elgeish, Building 11',
 'Suez, Arbeen, Elgeish, عمارة 120',
 'الدقهليه, Mansoura, Portsaid, Building 55',
 'الجيزه, Dokki, Mosadak, عمارة 59',
 'أسيوط, Assiuteast, Helaly, B31',
 'اسيوط, Assiut East, El Geish, B32',
 'Giza, Dokki, Tahrir, B65',
 'السويس, Arbeen, El Geish, عمارة 94',
 'Giza, Dokki, Tahrir, Building 37',
 'السويس, Arbeen, Elgeish, Building 82',
 'Assiut, Assiuteast, Helaly, B107',
 'Suez, Arbeen, El Geish, عمارة 105',
 'الإسكندرية, Smouha, Fawzymoaz, Building 31',
 'القاهره, Heliopolis, Orouba, عمارة 66',
 'القاهرة, New Cairo, South 90, B114',
 'Cairo, Newcairo, South90, B88',
 'Assiut, Assiuteast, Elgeish, Building 103',
 'Giza, Mohandseen, Gameateldowal, B54',
 'Assiut, Assiut East, Helaly, B10',
 'السويس, Arbeen, Elgeish, Building 107',
 'الجيزه, Dokki, Mosadak, Building 15',
 'Giza, Dokki, Mosadak, B100',
 'Assiut, Assiuteast, Helaly, B47',
 'Suez, Arbeen, El Geish, عمارة 88',
 'Assiut, Assiut East, El Geish, B12',
 'Assiut, Assiut East, Elgeish, Building 20',
 'Assiut, Assiut East, Helaly, B82',
 'الدقهليه, Mansoura, Portsaid, عمارة 13',
 'الإسكندرية, Lauran, Abdel Salam Aref, عمارة 25',
 'الاسكندريه, Miami, Khaled Ibn El Walid, B44',
 'Giza, Sheikh Zayed, Beverlyhills, B19',
 'اسيوط, Assiuteast, Helaly, Building 34',
 'Assiut, Assiut East, Elgeish, B63',
 'Alex, Lauran, Abdelsalamaref, Building 88',
 'الاسكندريه, Lauran, Abdelsalamaref, Building 2',
 'أسيوط, Assiut East, El Geish, B82',
 'Suez, Arbeen, Elgeish, Building 44',
 'Giza, Sheikhzayed, District1, عمارة 35',
 'القاهرة, Maadi, Laselky, Building 28',
 'الإسكندرية, Miami, Khaledibnelwalid, عمارة 19',
 'الدقهلية, Mansoura, Gomhoria, عمارة 96',
 'Alex, Smouha, Victor Emanuel, عمارة 53',
 'Suez, Arbeen, El Geish, عمارة 109',
 'Suez, Arbeen, El Geish, B79',
 'Dakahlia, Mansoura, Portsaid, B92',
 'Giza, Dokki, Tahrir, عمارة 23',
 'Cairo, Nasrcity, Makramebeid, Building 68',
 'Alex, Lauran, Abdel Salam Aref, عمارة 16',
 'الإسكندرية, Smouha, Fawzy Moaz, عمارة 73',
 'أسيوط, Assiuteast, Helaly, B82',
 'Cairo, Maadi, Street 9, عمارة 67',
 'الإسكندرية, Miami, Khaled Ibn El Walid, عمارة 37',
 'القاهرة, Newcairo, North 90, عمارة 35',
 'الاسكندريه, Lauran, Abdel Salam Aref, Building 64',
 'Suez, Arbeen, El Geish, B61',
 'Dakahlia, Mansoura, Gomhoria, Building 85',
 'اسيوط, Assiuteast, El Geish, B1',
 'أسيوط, Assiuteast, El Geish, Building 2',
 'اسيوط, Assiut East, El Geish, Building 98',
 'السويس, Arbeen, Elgeish, Building 69',
 'الدقهلية, Mansoura, Portsaid, عمارة 14',
 'الإسكندرية, Smouha, Victoremanuel, Building 4',
 'السويس, Arbeen, El Geish, عمارة 14',
 'أسيوط, Assiut East, Helaly, عمارة 50',
 'Alex, Miami, Khaledibnelwalid, B37',
 'الدقهليه, Mansoura, Portsaid, عمارة 6',
 'Dakahlia, Mansoura, Portsaid, Building 118',
 'Giza, Mohandseen, Gameateldowal, عمارة 13',
 'السويس, Arbeen, Elgeish, B40',
 'القاهره, Nasrcity, Mostafa El Nahas, Building 11',
 'الجيزة, Dokki, Mosadak, B81',
 'الجيزة, Sheikh Zayed, Beverlyhills, B107',
 'Cairo, Newcairo, 90Thstreet, B17',
 'Suez, Arbeen, Elgeish, B19',
 'Suez, Arbeen, El Geish, Building 68',
 'Dakahlia, Mansoura, Gomhoria, B33',
 'Alex, Lauran, Abdel Salam Aref, B36',
 'Cairo, Nasr City, Mostafa El Nahas, Building 35',
 'أسيوط, Assiut East, Helaly, عمارة 113',
 'Suez, Arbeen, Elgeish, Building 15',
 'الدقهلية, Mansoura, Portsaid, B35',
 'القاهرة, Heliopolis, Nozha, B30',
 'الدقهلية, Mansoura, Gomhoria, Building 33',
 'الدقهلية, Mansoura, Portsaid, عمارة 86',
 'Cairo, New Cairo, 90Th Street, عمارة 116',
 'اسيوط, Assiuteast, El Geish, عمارة 85',
 'القاهرة, Maadi, Degla, Building 36',
 'Cairo, New Cairo, South 90, B13',
 'القاهره, Maadi, Laselky, عمارة 56',
 'Suez, Arbeen, El Geish, Building 63',
 'القاهرة, Heliopolis, Merghany, Building 56',
 'Cairo, Nasrcity, Abbaselakkad, Building 78',
 'Giza, Sheikhzayed, Beverlyhills, B39',
 'الدقهليه, Mansoura, Gomhoria, عمارة 22',
 'السويس, Arbeen, Elgeish, عمارة 72',
 'السويس, Arbeen, El Geish, B40',
 'اسيوط, Assiut East, Helaly, Building 1',
 'الجيزه, Sheikhzayed, Beverlyhills, عمارة 118',
 'اسيوط, Assiuteast, Helaly, Building 70',
 'السويس, Arbeen, El Geish, Building 72',
 'الإسكندرية, Lauran, Abdelsalamaref, عمارة 97',
 'Giza, Sheikhzayed, Youthhousing, Building 112',
 'Giza, Sheikh Zayed, Youthhousing, Building 106',
 'Cairo, Nasrcity, Makramebeid, Building 89',
 'الإسكندرية, Lauran, Abdel Salam Aref, Building 78',
 'Suez, Arbeen, Elgeish, B82',
 'Suez, Arbeen, El Geish, عمارة 1',
 'القاهره, Nasr City, Mostafa El Nahas, B96',
 'القاهرة, Maadi, Degla, Building 35',
 'الدقهلية, Mansoura, Portsaid, B67',
 'Giza, Mohandseen, Gameateldowal, Building 22',
 'الإسكندرية, Miami, Khaledibnelwalid, Building 102',
 'الدقهليه, Mansoura, Portsaid, Building 13',
 'Assiut, Assiuteast, El Geish, عمارة 3',
 'اسيوط, Assiut East, Helaly, Building 108',
 'Dakahlia, Mansoura, Gomhoria, Building 65',
 'الاسكندريه, Lauran, Abdel Salam Aref, Building 119',
 'الإسكندرية, Lauran, Abdel Salam Aref, B25',
 'Giza, Dokki, Sudan, B48',
 'الإسكندرية, Miami, Khaled Ibn El Walid, Building 87',
 'الدقهليه, Mansoura, Portsaid, عمارة 118',
 'Giza, Sheikhzayed, Youthhousing, عمارة 1',

In [71]:

# Address Mapping Dictionary (Data Standardization)
# =======================================================
# Purpose: Converts messy Arabic/English addresses into clean English categories.
# Format:  'raw_input_text': ('City', 'Governorate')
# Benefit: Ensures accurate grouping and clean slicers for BI dashboards.

address_map = {
    # ===================== CAIRO – New Cairo =====================
    'new cairo': ('New Cairo', 'Cairo'),
    'newcairo': ('New Cairo', 'Cairo'),
    'القاهرة الجديدة': ('New Cairo', 'Cairo'),
    'التجمع الخامس': ('New Cairo', 'Cairo'),
    'fifth settlement': ('New Cairo', 'Cairo'),
    '90th street': ('New Cairo', 'Cairo'),
    '90th st': ('New Cairo', 'Cairo'),
    '90thstreet': ('New Cairo', 'Cairo'),
    'north 90': ('New Cairo', 'Cairo'),
    'south 90': ('New Cairo', 'Cairo'),
    'south ninety': ('New Cairo', 'Cairo'),
    '90 street': ('New Cairo', 'Cairo'),

    # ===================== CAIRO – Nasr City =====================
    'nasr city': ('Nasr City', 'Cairo'),
    'nasrcity': ('Nasr City', 'Cairo'),
    'مدينة نصر': ('Nasr City', 'Cairo'),
    'عباس العقاد': ('Nasr City', 'Cairo'),
    'abbas el akkad': ('Nasr City', 'Cairo'),
    'abbaselakkad': ('Nasr City', 'Cairo'),
    'makram ebeid': ('Nasr City', 'Cairo'),
    'makramebeid': ('Nasr City', 'Cairo'),
    'mostafa elnahas': ('Nasr City', 'Cairo'),

    # ===================== CAIRO – Maadi =====================
    'maadi': ('Maadi', 'Cairo'),
    'المعادي': ('Maadi', 'Cairo'),

    # ===================== CAIRO – Heliopolis =====================
    'heliopolis': ('Heliopolis', 'Cairo'),
    'مصر الجديدة': ('Heliopolis', 'Cairo'),
    'merghany': ('Heliopolis', 'Cairo'),
    'المرغني': ('Heliopolis', 'Cairo'),

    # ===================== GIZA – Sheikh Zayed =====================
    'sheikh zayed': ('Sheikh Zayed', 'Giza'),
    'sheikhzayed': ('Sheikh Zayed', 'Giza'),
    'الشيخ زايد': ('Sheikh Zayed', 'Giza'),
    'youth housing': ('Sheikh Zayed', 'Giza'),
    'الاسكان الشبابي': ('Sheikh Zayed', 'Giza'),

    # ===================== GIZA – 6th of October =====================
    '6 october': ('6th Of October', 'Giza'),
    '6 أكتوبر': ('6th Of October', 'Giza'),
    '6thofoctober': ('6th Of October', 'Giza'),
    'october': ('6th Of October', 'Giza'),

    # ===================== GIZA – Dokki =====================
    'dokki': ('Dokki', 'Giza'),
    'الدقي': ('Dokki', 'Giza'),
    'tahrir': ('Dokki', 'Giza'),
    'التحرير': ('Dokki', 'Giza'),

    # ===================== GIZA – Mohandseen =====================
    'mohandseen': ('Mohandseen', 'Giza'),
    'المهندسين': ('Mohandseen', 'Giza'),
    'shehab': ('Mohandseen', 'Giza'),
    'lebanon': ('Mohandseen', 'Giza'),
    'لبنان': ('Mohandseen', 'Giza'),

    # ===================== ALEXANDRIA – Miami =====================
    'miami': ('Miami', 'Alexandria'),
    'ميامي': ('Miami', 'Alexandria'),
    'khaled ibn el walid': ('Miami', 'Alexandria'),
    'khaled ibnelwalid': ('Miami', 'Alexandria'),
    'khaledibnelwalid': ('Miami', 'Alexandria'),

    # ===================== ALEXANDRIA – Smouha =====================
    'smouha': ('Smouha', 'Alexandria'),
    'سموحة': ('Smouha', 'Alexandria'),
    'fawzy moaz': ('Smouha', 'Alexandria'),
    'fawzymoaz': ('Smouha', 'Alexandria'),
    'victor emanuel': ('Smouha', 'Alexandria'),
    'victoremanuel': ('Smouha', 'Alexandria'),

    # ===================== ALEXANDRIA – Lauran (+ generic "Alex" fallback) =====================
    'lauran': ('Lauran', 'Alexandria'),
    'لوران': ('Lauran', 'Alexandria'),
    'abdel salam aref': ('Lauran', 'Alexandria'),
    'abdelsalamaref': ('Lauran', 'Alexandria'),
    'alex': ('Lauran', 'Alexandria'),
    'alexandria': ('Lauran', 'Alexandria'),
    'الاسكندرية': ('Lauran', 'Alexandria'),
    'الإسكندرية': ('Lauran', 'Alexandria'),

    # ===================== DAKAHLIA – Mansoura =====================
    'mansoura': ('Mansoura', 'Dakahlia'),
    'المنصورة': ('Mansoura', 'Dakahlia'),
    'portsaid': ('Mansoura', 'Dakahlia'),   # street/area inside Mansoura, NOT Port Said governorate
    'بورسعيد': ('Mansoura', 'Dakahlia'),

    # ===================== ASSIUT – Assiut East =====================
    'assiut east': ('Assiut East', 'Assiut'),
    'assiuteast': ('Assiut East', 'Assiut'),
    'helaly': ('Assiut East', 'Assiut'),
    'الهلالي': ('Assiut East', 'Assiut'),

    # ===================== SUEZ – Arbeen =====================
    'arbeen': ('Arbeen', 'Suez'),
    'العربين': ('Arbeen', 'Suez'),
    'el geish': ('Arbeen', 'Suez'),   # also occurs under Assiut East, but 'assiut east' key above wins for those rows
    'elgeish': ('Arbeen', 'Suez'),

    # ===================== GENERIC GOVERNORATE FALLBACKS (lowest priority — keep last) =====================
    'giza': ('Giza', 'Giza'),
    'الجيزة': ('Giza', 'Giza'),
    'الجيزه': ('Giza', 'Giza'),
    'cairo': ('Cairo', 'Cairo'),
    'القاهرة': ('Cairo', 'Cairo'),
    'القاهره': ('Cairo', 'Cairo'),
    'assiut': ('Assiut', 'Assiut'),
    'اسيوط': ('Assiut', 'Assiut'),
    'أسيوط': ('Assiut', 'Assiut'),
    'suez': ('Suez', 'Suez'),
    'السويس': ('Suez', 'Suez'),
}

In [72]:
# Apply Mapping Function
# =======================================================
# Purpose: Scans the raw address for keywords from 'address_map'.
# Output:  Returns [City, Governorate] as a Pandas Series to create new columns.
# Fallback: Returns 'Unknown' if no keyword is found.

def map_address(addr):
    addr = str(addr).lower()
    for key, (city, gov) in address_map.items():
        if key in addr:
            return pd.Series([city, gov])
    return pd.Series(['Unknown', 'Unknown'])

In [73]:
# Execute Mapping & Create Columns
# =======================================================
# Purpose: Applies the mapping function to the entire 'address' column.
# Action:  Unpacks the results into two new clean columns: 'city' and 'governorate'.

df[['city', 'governorate']] = df['address'].apply(map_address)

In [74]:
df[['address', 'city', 'governorate']].head(10)

                                        address          city governorate
0  الجيزة, Sheikhzayed, Youth Housing, عمارة 12  Sheikh Zayed        Giza
1        الدقهلية, Mansoura, Portsaid, عمارة 64      Mansoura    Dakahlia
2       Assiut, Assiut East, El Geish, عمارة 23   Assiut East      Assiut
3      Assiut, Assiut East, Helaly, Building 80   Assiut East      Assiut
4              اسيوط, Assiuteast, El Geish, B60   Assiut East      Assiut
5                الجيزة, Dokki, Tahrir, عمارة 6         Dokki        Giza
6            السويس, Arbeen, El Geish, عمارة 24        Arbeen        Suez
7            Suez, Arbeen, Elgeish, Building 53        Arbeen        Suez
8    Alex, Miami, Khaledibnelwalid, Building 20         Miami  Alexandria
9          السويس, Arbeen, Elgeish, Building 97        Arbeen        Suez

In [75]:
# Quality Assurance (QA) & Error Handling
# Purpose: Identifies any addresses that failed the mapping process.

df[df['city'] == 'Unknown']['address'].value_counts().head(10)

Series([], Name: count, dtype: int64)

In [76]:
# Export the fully cleaned and engineered customers dimension table to a new CSV file
df.to_csv("customers_cleaned.csv", index=False)

## Phase 5: Data Integration 

This final phase focuses on merging the cleaned Fact and Dimension tables into a single, flat denormalized dataset (OBT) ready for analysis.

**Key Objectives:**
* **Data Integration:** Merging the core `sales` table with `customers` and `projects` dimensions using their primary keys.
* **Denormalization:** Flattening the data into one comprehensive CSV to simplify querying and dashboard reporting.
* **Data Integrity:** Enforcing `Left Joins` across all merges to guarantee zero loss of core sales transactions.

In [77]:
import pandas as pd

sales_df = pd.read_csv("sales_cleaned.csv")
customers_df = pd.read_csv("customers_cleaned.csv")

# Merge Sales (Fact) with Customers (Dim) using Left Join to keep all transactions
sales_customers_df = pd.merge(
    sales_df,
    customers_df,
    on="customer_id",
    how="left"
)

In [78]:
sales_customers_df.head()

,sale_id,sale_date,customer_id,project_id,unit_type,unit_price,discount,final_price,payment_plan,down_payment,...,customer_type,lead_source,budget_range,created_at,sales_agent,segment,created_year,created_month,city,governorate
0,S2023010000000,2023-01-14,CUST_22585,PRJ_30,3Br,6691492,100000,6591492,8Y,938086.13,...,Individual,Referral,2-3M,2023-11-27,Ali,Vip,2023,11,Assiut East,Assiut
1,S2023010000001,2023-01-17,CUST_23621,PRJ_19,Studio,2846816,100000,2746816,Cash,313545.17,...,Company,Event,1-2M,2023-04-29,Ahmed,Normal,2023,4,Assiut East,Assiut
2,S2023010000002,2023-01-19,CUST_12281,PRJ_4,Villa,1357382,0,1357382,8Y,196379.95,...,Individual,Whatsapp,3-5M,2025-07-27,Mohamed,New,2025,7,New Cairo,Cairo
3,S2023010000003,2023-01-11,CUST_8266,PRJ_18,2Br,2363226,100000,2263226,Cash,554752.04,...,Company,Whatsapp,3-5M,2023-08-17,Ali,New,2023,8,Heliopolis,Cairo
4,S2023010000004,2023-01-18,CUST_14652,PRJ_34,3Br,5212700,0,5212700,5Y,1536354.55,...,Company,Event,3-5M,2024-09-30,Ali,Vip,2024,9,New Cairo,Cairo

In [79]:
# Save the merged dataset to a new CSV (index=False prevents exporting the row numbers as an extra column)
sales_customers_df.to_csv("sales_with_customers.csv", index=False)

In [80]:
import pandas as pd

sales_customers_df = pd.read_csv("sales_with_customers.csv")
projects_df = pd.read_csv("projects_cleaned.csv")

# Merge the combined Sales & Customers data with the Projects Dimension table
final_df = pd.merge(
    sales_customers_df,
    projects_df,
    on="project_id",
    how="left"
)

In [81]:
final_df.shape

(1080000, 44)

In [82]:
# Save the final, fully merged Master Table to a new CSV (without exporting the row index)
final_df.to_csv("sales_full_dataset.csv", index=False)